version: '3.8'
services:
  client:
    build: ./client
    image: image-client
    container_name: client-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - NEWNRG_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: image-server
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/newnrg

  db:
    image: postgres:13.7-alpine
    container_name: db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=newnrg
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password