CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    user_password VARCHAR(255),
    user_role VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS equipment (
    equipment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operational_name VARCHAR(255),
    installation_year SMALLINT,
    type_id INT REFERENCES types(type_id) ON DELETE CASCADE,

    );

CREATE TABLE IF NOT EXISTS projects (
    project_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(255),
    project_code VARCHAR(255),
    file VARCHAR(55)
);

CREATE TABLE IF NOT EXISTS equipment_projects (
    equipment_id INT REFERENCES equipment(equipment_id) ON DELETE CASCADE,
    project_id INT REFERENCES projects(project_id) ON DELETE CASCADE,
    PRIMARY KEY (equipment_id, project_id)
);

