CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    user_password VARCHAR(255),
    user_role VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS equipment (
    equipment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operational_name VARCHAR(255),
    rated_current VARCHAR(255),
    rated_voltage VARCHAR(255)
);

